import { StylesProvider } from './styles-provider'
import { ThemeProvider } from './theme-provider'
import './globals.css'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <StylesProvider>{children}</StylesProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
